/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        intern: ['INTERN', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        sans: ['INTERN', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
      },
      colors: {
        bg: {
          primary: 'var(--color-bg-primary)',
          secondary: 'var(--color-bg-secondary)',
          surface: 'var(--color-bg-surface)',
          muted: 'var(--color-bg-muted)',
          dark: 'var(--color-bg-dark)',
          darkSoft: 'var(--color-bg-dark-soft)',
          darkElevated: 'var(--color-bg-dark-elevated)',
        },
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          muted: 'var(--color-text-muted)',
          subtle: 'var(--color-text-subtle)',
          inverse: 'var(--color-text-inverse)',
          inverseSecondary: 'var(--color-text-inverse-secondary)',
          inverseMuted: 'var(--color-text-inverse-muted)',
        },
        border: {
          DEFAULT: 'var(--color-border)',
          subtle: 'var(--color-border-subtle)',
          strong: 'var(--color-border-strong)',
          dark: 'var(--color-border-dark)',
          darkSubtle: 'var(--color-border-dark-subtle)',
        },
        accent: {
          DEFAULT: 'var(--color-accent)',
          hover: 'var(--color-accent-hover)',
          contrast: 'var(--color-accent-contrast)',
          subtle: 'var(--color-accent-subtle)',
        },
        mono: {
          950: '#0a0a0a',
          900: '#121212',
          850: '#151515',
          800: '#222222',
          750: '#2a2a2a',
          700: '#3a3a3a',
          600: '#4a4a4a',
          500: '#777777',
          400: '#9e9e9e',
          300: '#dcdcdc',
          200: '#e8e8e6',
          100: '#f0f0ee',
          50: '#f5f5f3',
          0: '#ffffff',
        }
      },
      fontSize: {
        'display-2xl': ['clamp(3.5rem, 8vw, 6.5rem)', { lineHeight: '1.02', letterSpacing: '-0.035em' }],
        'display-xl': ['clamp(2.75rem, 6.5vw, 5.25rem)', { lineHeight: '1.05', letterSpacing: '-0.03em' }],
        'display-lg': ['clamp(2.25rem, 4.5vw, 3.75rem)', { lineHeight: '1.08', letterSpacing: '-0.025em' }],
        'display-md': ['clamp(1.85rem, 3.5vw, 2.75rem)', { lineHeight: '1.15', letterSpacing: '-0.02em' }],
        
        'heading-xl': ['clamp(1.75rem, 3vw, 2.5rem)', { lineHeight: '1.18', letterSpacing: '-0.02em' }],
        'heading-lg': ['clamp(1.4rem, 2.2vw, 2rem)', { lineHeight: '1.22', letterSpacing: '-0.018em' }],
        'heading-md': ['clamp(1.2rem, 1.6vw, 1.55rem)', { lineHeight: '1.28', letterSpacing: '-0.015em' }],
        'heading-sm': ['1.125rem', { lineHeight: '1.35', letterSpacing: '-0.01em' }],
        'heading-xs': ['1rem', { lineHeight: '1.4', letterSpacing: '-0.005em' }],

        'body-lg': ['1.125rem', { lineHeight: '1.65', letterSpacing: '-0.005em' }],
        'body-md': ['1rem', { lineHeight: '1.6', letterSpacing: '0' }],
        'body': ['1rem', { lineHeight: '1.6', letterSpacing: '0' }],
        'body-sm': ['0.875rem', { lineHeight: '1.55', letterSpacing: '0.005em' }],

        'eyebrow': ['0.75rem', { lineHeight: '1.2', letterSpacing: '0.12em' }],
        'label': ['0.75rem', { lineHeight: '1.2', letterSpacing: '0.08em' }],
        'caption': ['0.75rem', { lineHeight: '1.45', letterSpacing: '0.02em' }],
        'nav': ['0.875rem', { lineHeight: '1.25', letterSpacing: '-0.01em' }],
        'button': ['0.875rem', { lineHeight: '1.25', letterSpacing: '-0.01em' }],
      },
      spacing: {
        '4.5': '1.125rem',
        '18': '4.5rem',
        '22': '5.5rem',
        '26': '6.5rem',
        '30': '7.5rem',
        '34': '8.5rem',
        '38': '9.5rem',
        '13': '3.25rem',
        'section-xs': 'var(--section-xs)',
        'section-sm': 'var(--section-sm)',
        'section-md': 'var(--section-md)',
        'section-lg': 'var(--section-lg)',
        'section-xl': 'var(--section-xl)',
      },
      boxShadow: {
        subtle: 'var(--shadow-subtle)',
        card: 'var(--shadow-card)',
        floating: 'var(--shadow-floating)',
      },
      borderRadius: {
        'none': '0px',
        'xs': '2px',
        'sm': '4px',
        'DEFAULT': '4px',
        'md': '6px',
        'lg': '8px',
      },
      maxWidth: {
        'content': 'var(--container-max-width)',
        'narrow': 'var(--container-narrow-width)',
        'prose': '65ch',
      },
      zIndex: {
        'base': 'var(--z-base)',
        'content': 'var(--z-content)',
        'sticky': 'var(--z-sticky)',
        'navbar': 'var(--z-navbar)',
        'mobile-menu': 'var(--z-mobile-menu)',
        'modal': 'var(--z-modal)',
        'toast': 'var(--z-toast)',
        'skip-link': 'var(--z-skip-link)',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
      animation: {
        'fade-in': 'fadeIn 0.25s cubic-bezier(0.16, 1, 0.3, 1) forwards',
      },
      transitionTimingFunction: {
        'standard': 'var(--ease-standard)',
        'emphasized': 'var(--ease-emphasized)',
        'luxury': 'var(--ease-luxury)',
      },
      transitionDuration: {
        'instant': 'var(--motion-instant)',
        'fast': 'var(--motion-fast)',
        'normal': 'var(--motion-normal)',
        'slow': 'var(--motion-slow)',
        'luxury': 'var(--motion-luxury)',
      }
    },
  },
  plugins: [],
};
